# Generated by Django 3.0.3 on 2020-05-29 10:18

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForModeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=index.models.upload_path)),
            ],
        ),
    ]
